# Generated by Django 2.2.6 on 2020-09-18 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_profilephoto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilephoto',
            unique_together={('user', 'photo')},
        ),
    ]
